!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: DeathZone
  1: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: BadGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: DeathZone
  2: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
    - !Item
      name: Wall
      colors:
  3: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Ramp
    - !Item
      name: Wall
  4: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Ramp
    - !Item
      name: Wall
  5: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalMulti
    - !Item
      name: Ramp
    - !Item
      name: Ramp
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: Wall
    - !Item
      name: Wall
  6: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Ramp
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: Wall
  7: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  8: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
    - !Item
      name: Wall
  9: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  10: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
    - !Item
      name: Wall
    - !Item
      name: Wall
  11: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  12: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
    - !Item
      name: Wall
  13: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Ramp
      colors:
      - !RGB {r: 255, g: 0, b: 255}
      - !RGB {r: 255, g: 0, b: 255}
      - !RGB {r: 255, g: 0, b: 255}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
  14: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Ramp
      colors:
      - !RGB {r: 255, g: 0, b: 255}
      - !RGB {r: 255, g: 0, b: 255}
      - !RGB {r: 255, g: 0, b: 255}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
  15: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
    - !Item
      name: Wall
  16: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  17: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Ramp
    - !Item
      name: Ramp
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: Wall
  18: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: DeathZone
    - !Item
      name: Wall
    - !Item
      name: Wall
  19: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
    - !Item
      name: Wall
  20: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: Wall
    - !Item
      name: Wall
  21: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: Wall
    - !Item
      name: Wall
      colors:
  22: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
    - !Item
      name: DeathZone
  23: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
