!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 20, y: 0, z: 20}
      - !Vector3 {x: 20, y: 0, z: 8.75}
      - !Vector3 {x: 20, y: 0, z: 31.25}
      - !Vector3 {x: 8.75, y: 0, z: 20}
      - !Vector3 {x: 31.25, y: 0, z: 20}
      rotations: [0,0,0,0,0]
      sizes: 
      - !Vector3 {x: 5, y: 0.5, z: 5}
      - !Vector3 {x: .1, y: 5, z: 17.5}
      - !Vector3 {x: .1, y: 5, z: 17.5}
      - !Vector3 {x: 17.5, y: 5, z: .1}
      - !Vector3 {x: 17.5, y: 5, z: .1}
      colors:
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 200, g: 200, b: 200}
      - !RGB {r: 200, g: 200, b: 200}
      - !RGB {r: 200, g: 200, b: 200}
      - !RGB {r: 200, g: 200, b: 200}
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 20, y: .5, z: 20}
      rotations: [0]
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 30, y: 0, z: 30}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: BadGoal
      positions: 
      - !Vector3 {x: 10, y: 0, z: 30}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}