!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Cardbox1
    - !Item
      name: Cardbox2
    - !Item
      name: UObject
    - !Item
      name: LObject
