!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
    - !Item
      name: Wall
      rotations: [90,90,90,0,0,0]
      sizes:
      - !Vector3 {x: 1, y: 5, z: 9}
      - !Vector3 {x: 1, y: 5, z: 9}
      - !Vector3 {x: 1, y: 5, z: 9}
      - !Vector3 {x: 1, y: 5, z: 9}
      - !Vector3 {x: 1, y: 5, z: 9}
      - !Vector3 {x: 1, y: 5, z: 9}
    - !Item
      name: GoodGoal
      positions:
        - !Vector3 {x: -1, y: 0, z: 35}
