!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Ramp
    - !Item
      name: Ramp
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: Wall
    - !Item
      name: WallTransparent
