!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 3, y: 0, z: -1}
      - !Vector3 {x: 3, y: 0, z: -1}
      - !Vector3 {x: 37, y: 0, z: -1}
      - !Vector3 {x: 37, y: 0, z: -1}
      - !Vector3 {x: -1, y: 0, z: -1}
      - !Vector3 {x: -1, y: 0, z: -1}
      - !Vector3 {x: -1, y: 0, z: -1}
      - !Vector3 {x: -1, y: 0, z: -1}
      - !Vector3 {x: -1, y: 0, z: 37}
      - !Vector3 {x: -1, y: 0, z: 37}
      - !Vector3 {x: -1, y: 0, z: 3}
      - !Vector3 {x: -1, y: 0, z: 3}
      colors:
      rotations: [90,90,90,90,90,90,90,0,0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: 1, y: 5, z: 6}
      - !Vector3 {x: 1, y: 5, z: 6}
      - !Vector3 {x: 1, y: 5, z: 6}
      - !Vector3 {x: 1, y: 5, z: 6}
      - !Vector3 {x: 1, y: 5, z: 6}
      - !Vector3 {x: 1, y: 5, z: 6}
      - !Vector3 {x: 1, y: 5, z: 6}
      - !Vector3 {x: 1, y: 5, z: 6}
      - !Vector3 {x: 1, y: 5, z: 6}
      - !Vector3 {x: 1, y: 5, z: 6}
      - !Vector3 {x: 1, y: 5, z: 6}
      - !Vector3 {x: 1, y: 5, z: 6}
    - !Item
      name: GoodGoalMulti
      positions:
        - !Vector3 {x: -1, y: 0, z: 35}
        - !Vector3 {x: -1, y: 0, z: 20}
    - !Item
      name: Agent
      positions:
        - !Vector3 {x: 39, y: 1, z: -1}