!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: WallTransparent
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
    - !Item
      name: DeathZone
      sizes:
      - !Vector3 {x: 3, y: 0, z: 9}
      name: DeathZone
      sizes:
      - !Vector3 {x: 1, y: 0, z: 9}
