!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: -1, y: 0, z: 10}
      - !Vector3 {x: -1, y: 0, z: 20}
      - !Vector3 {x: -1, y: 0, z: 30}
      - !Vector3 {x: 10, y: 0, z: -1}
      - !Vector3 {x: 20, y: 0, z: -1}
      - !Vector3 {x: 30, y: 0, z: -1}
      colors:
      rotations: [90,90,90,0,0,0]
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
      - !Vector3 {x: 5, y: 5, z: 5}
      - !Vector3 {x: 5, y: 5, z: 5}
      - !Vector3 {x: 5, y: 5, z: 5}
      - !Vector3 {x: 5, y: 5, z: 5}
      - !Vector3 {x: 5, y: 5, z: 5}
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: Agent
