!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: GoodGoalMultiBounce
      positions:
        - !Vector3 {x: 20, y: 0, z: 20}
        - !Vector3 {x: -1, y: 0, z: -1}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Ramp
    - !Item
      name: Ramp
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: Wall
    - !Item
      name: Wall
