!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 37.5, y: 0, z: 20}
      colors:
      rotations: [0]
      sizes:
      - !Vector3 {x: 5, y: 3, z: 40}
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      colors:
      rotations: [270]
      sizes:
      - !Vector3 {x: -1, y: 3, z: 30}
    - !Item
      name: GoodGoalMulti
      positions:
        - !Vector3 {x: 37, y: 4, z: -1}
    - !Item
      name: Agent
      positions:
        - !Vector3 {x: 1, y: 1, z: -1}
       

