!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 16}
      - !Vector3 {x: 30, y: 0, z: 24}
      - !Vector3 {x: 5, y: 0, z: 5}
      colors:
      rotations: [0,0, -1]
      sizes:
      - !Vector3 {x: 1, y: -1, z: 32}
      - !Vector3 {x: 1, y: -1, z: 32}
      - !Vector3 {x: -1, y: -1, z: -1}
    - !Item
      name: GoodGoal
    - !Item
      name: GoodMulti
