!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
    - !Item
      name: Wall
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
