!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: WallTransparent
    - !Item
      name: WallTransparent
    - !Item
      name: Wall
    - !Item
      name: Wall
