!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalMulti
    - !Item
      name: Ramp
    - !Item
      name: Ramp
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: Wall
    - !Item
      name: Wall