!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}