!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalMulti
      positions:
        - !Vector3 {x: 39, y: -1, z: 39}
        - !Vector3 {x: 39, y: -1, z: 20}
        - !Vector3 {x: 39, y: -1, z: 0}
        - !Vector3 {x: 1, y: -1, z: 39}
        - !Vector3 {x: 1, y: -1, z: 1}
        - !Vector3 {x: 20, y: -1, z: 20}
    - !Item
      name: Agent
      positions:
        - !Vector3 {x: -1, y: -1, z: 1}

