!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: UObject
    - !Item
      name: LObject
    - !Item
      name: LObject
    - !Item
      name: LObject
    - !Item
      name: LObject2
    - !Item
      name: Cardbox1
    - !Item
      name: Cardbox2
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
    - !Item
      name: GoodGoalMulti
    - !Item
      name: Agent

