!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      colors:
      rotations: [180]
      sizes:
      - !Vector3 {x: 40, y: 3, z: 30}
    - !Item
      name: GoodGoalMulti
      positions:
        - !Vector3 {x: -1, y: 4, z: 37}
    - !Item
      name: Agent
      positions:
        - !Vector3 {x: -1, y: 1, z: 1}
       

