!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 40, y: -1, z: 40}
      rotations: [0]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 15, y: 0, z: 15}
      - !Vector3 {x: 15, y: 0, z: 25}
      colors:
      rotations: [0,0,0]
      sizes:
      - !Vector3 {x: 10, y: 4, z: 10}
      - !Vector3 {x: 10, y: 4, z: 10}
      - !Vector3 {x: 10, y: 4, z: 10}
    - !Item
      name: GoodGoalMulti
      positions:
    - !Item
      name: Agent
      positions:
        - !Vector3 {x: 1, y: 5, z: 1}

