!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 30, y: 0, z: -1}
      colors:
      rotations: [-1]
      sizes:
      - !Vector3 {x: 1, y: -1, z: 32}
    - !Item
      name: GoodGoal
      positions:
        - !Vector3 {x: 35, y: 0, z: -1}
      name: GoodGoalMulti
    - !Item
      name: Wall
    - !Item
      name: Agent

