!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 10, y: 0, z: -1}
      colors:
      rotations: [0]
      sizes:
      - !Vector3 {x: 1, y: -1, z: 8}
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoalBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: BadGoalBounce

