!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: -1, y: 0, z: 30}
      colors:
      rotations: [0]
      sizes:
      - !Vector3 {x: 32, y: -1, z: 1}
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoalBounce
      positions:
    - !Item
      name: Agent
 

