!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 40, y: -1, z: 2}
      rotations: [0]
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 5, y: 0, z: 20}
      colors:
      rotations: [180]
      sizes:
      - !Vector3 {x: 4, y: 3, z: 4}
    - !Item
      name: Wall
      positions:
        - !Vector3 {x: 5, y: 0, z: 25}
        - !Vector3 {x: 18, y: 0, z: 25}
        - !Vector3 {x: 25, y: 0, z: 12}
      colors:
      rotations: [0, 0, 0]
      sizes:
      - !Vector3 {x: 4, y: 3, z: 4}
      - !Vector3 {x: 20, y: 3, z: 4}
      - !Vector3 {x: 20, y: 3, z: 20}
    - !Item
      name: GoodGoalMulti
      positions:
        - !Vector3 {x: -1, y: 4, z: -1}
        - !Vector3 {x: -1, y: 4, z: -1}
    - !Item
      name: Agent
      positions:
        - !Vector3 {x: -1, y: 1, z: 1}
       

