!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 40, y: -1, z: 5}
      rotations: [0]
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: -1, y: 0, z: 18}
      colors:
      rotations: [180]
      sizes:
      - !Vector3 {x: -1, y: 2, z: -1}
    - !Item
      name: Wall
      positions:
      colors:
      rotations:
      sizes:
      - !Vector3 {x: 1, y: -1, z: 16}
    - !Item
      name: GoodGoal
      positions:
        - !Vector3 {x: -1, y: 0, z: 30}
    - !Item
      name: Agent
      positions:
        - !Vector3 {x: -1, y: 1, z: 0}

