!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: CylinderTunnel
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: WallTransparent
    - !Item
      name: Cardbox1
    - !Item
      name: Cardbox2
    - !Item
      name: Cylinder
    - !Item
      name: UObject
    - !Item
      name: LObject
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalBounce
    - !Item
      name: BadGoal
    - !Item
      name: BadGoalBounce
    - !Item
      name: GoodGoalMulti
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  1: !Arena
    t: 0
    items:
    - !Item
      name: CylinderTunnel
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: WallTransparent
    - !Item
      name: Cardbox1
    - !Item
      name: Cardbox2
    - !Item
      name: Cylinder
    - !Item
      name: UObject
    - !Item
      name: LObject
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalBounce
    - !Item
      name: BadGoal
    - !Item
      name: BadGoalBounce
    - !Item
      name: GoodGoalMulti
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  2: !Arena
    t: 0
    items:
    - !Item
      name: CylinderTunnel
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: WallTransparent
    - !Item
      name: Cardbox1
    - !Item
      name: Cardbox2
    - !Item
      name: Cylinder
    - !Item
      name: UObject
    - !Item
      name: LObject
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalBounce
    - !Item
      name: BadGoal
    - !Item
      name: BadGoalBounce
    - !Item
      name: GoodGoalMulti
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  3: !Arena
    t: 0
    items:
    - !Item
      name: CylinderTunnel
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: WallTransparent
    - !Item
      name: Cardbox1
    - !Item
      name: Cardbox2
    - !Item
      name: Cylinder
    - !Item
      name: UObject
    - !Item
      name: LObject
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalBounce
    - !Item
      name: BadGoal
    - !Item
      name: BadGoalBounce
    - !Item
      name: GoodGoalMulti
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
