!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: DeathZone
  1: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: DeathZone
  2: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Ramp
      colors:
      - !RGB {r: 255, g: 0, b: 255}
      - !RGB {r: 255, g: 0, b: 255}
      - !RGB {r: 255, g: 0, b: 255}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
  3: !Arena
    t: 500
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Ramp
      colors:
      - !RGB {r: 255, g: 0, b: 255}
      - !RGB {r: 255, g: 0, b: 255}
      - !RGB {r: 255, g: 0, b: 255}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
  4: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Ramp
      colors:
      - !RGB {r: 255, g: 0, b: 255}
      - !RGB {r: 255, g: 0, b: 255}
      - !RGB {r: 255, g: 0, b: 255}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
  5: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Ramp
    - !Item
      name: Ramp
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: Wall
  6: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Ramp
    - !Item
      name: Ramp
    - !Item
      name: Ramp
    - !Item
      name: Wall
  7: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  8: !Arena
    t: 500
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: BadGoalBounce
    - !Item
      name: BadGoalBounce
  9: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  10: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  11: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  12: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  13: !Arena
    t: 250
    items:
    - !Item
      name: CylinderTunnel
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: WallTransparent
    - !Item
      name: Cardbox1
    - !Item
      name: Cardbox2
    - !Item
      name: Cylinder
    - !Item
      name: UObject
    - !Item
      name: LObject
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalBounce
    - !Item
      name: BadGoal
    - !Item
      name: BadGoalBounce
    - !Item
      name: GoodGoalMulti
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  14: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalMultiBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  15: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalMultiBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  16: !Arena
    t: 500
    items:
    - !Item
      name: CylinderTunnel
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: WallTransparent
    - !Item
      name: Cardbox1
    - !Item
      name: Cardbox2
    - !Item
      name: Cylinder
    - !Item
      name: UObject
    - !Item
      name: LObject
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalBounce
    - !Item
      name: BadGoal
    - !Item
      name: BadGoalBounce
    - !Item
      name: GoodGoalMulti
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  17: !Arena
    t: 500
    items:
    - !Item
      name: CylinderTunnel
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: WallTransparent
    - !Item
      name: Cardbox1
    - !Item
      name: LObject
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalBounce
    - !Item
      name: BadGoal
    - !Item
      name: BadGoalBounce
    - !Item
      name: GoodGoalMulti
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: DeathZone
    - !Item
      name: HotZone
  18: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  19: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  20: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  21: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  22: !Arena
    t: 500
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
  23: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
