!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 15, y: 5, z: 15}
    - !Item
      name: Cardbox1
    - !Item
      name: Cardbox1
      sizes:
      - !Vector3 {x: 2, y: 3, z: 2}
      positions:
      - !Vector3 {x: 15, y: 0, z: 15}
    - !Item
      name: Cardbox2
    - !Item
      name: UObject
    - !Item
      name: LObject
